title: João Pedro Gomes dos Santos
description: AI / Systems Engineer | Computational Neuroscience PhD
author: João Pedro Gomes dos Santos
email: jpgs.12390@gmail.com
baseurl: ""
url: "https://jpgsantos.github.io"

# Social links
github_username: jpgsantos
linkedin_username: joaosantos1992

# Open Graph / Social Sharing
og_image: /assets/images/og-share.png
twitter:
  card: summary_large_image

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed
  sourcemap: never

exclude:
  - _site_preview/

# Navigation
header_pages:
  - index.md
  - projects.md
  - cv.md

# Custom variables
location: "Copenhagen, Amsterdam or Remote"
position: "AI / Systems Engineer | Computational Neuroscience PhD"
available: false
